# Generated by Django 2.2.7 on 2019-11-06 11:52

from django.db import migrations, models
import django.db.models.deletion
import graphqltest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSED')], default=graphqltest.models.Status(0))),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='graphqltest.Master')),
            ],
        ),
    ]
